import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    ButtonModule,
    GrowlModule,
    MessagesModule,
    MessageModule,
    MenuModule,
    PanelMenuModule,
    InputTextModule,
    CalendarModule,
    DropdownModule,
    DataTableModule,
    DialogModule,
    ConfirmDialogModule,
    PanelModule,
    CheckboxModule,
    ListboxModule,
    MultiSelectModule,
    InputSwitchModule,
    SelectButtonModule,
    PaginatorModule,
    TriStateCheckboxModule,
} from 'primeng/primeng'

@NgModule({
    imports: [
        CommonModule,
        ButtonModule,
        GrowlModule,
        MessagesModule,
        MessageModule,
        MenuModule,
        PanelMenuModule,
        InputTextModule,
        CalendarModule,
        DropdownModule,
        DataTableModule,
        DialogModule,
        ConfirmDialogModule,
        PanelModule,
        CheckboxModule,
        ListboxModule,
        MultiSelectModule,
        InputSwitchModule,
        SelectButtonModule,
        PaginatorModule,
        TriStateCheckboxModule,
    ],
    exports: [
        ButtonModule,
        GrowlModule,
        MessagesModule,
        MessageModule,
        MenuModule,
        PanelMenuModule,
        InputTextModule,
        CalendarModule,
        DropdownModule,
        DataTableModule,
        DialogModule,
        ConfirmDialogModule,
        PanelModule,
        CheckboxModule,
        ListboxModule,
        MultiSelectModule,
        InputSwitchModule,
        SelectButtonModule,
        PaginatorModule,
        TriStateCheckboxModule,
    ],
})
export class PrmngModule { }
